pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: yarn --frozen-lockfile
    displayName: Install dependencies

  - script: yarn lint
    displayName: Lint

  - script: yarn build
    displayName: Build

  - script: yarn jest --ci --reporters=default --reporters=jest-junit --coverage --coverageReporters=cobertura --coverageReporters=text
    displayName: Test

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFiles: junit.xml

  - task: PublishCodeCoverageResults@1
    displayName: Publish coverage results
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: coverage/cobertura-coverage.xml
