pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Gradle@2
    displayName: Build parser
    inputs:
      cwd: rascal-parser

  - script: yarn --frozen-lockfile
    displayName: Install plugin dependencies

  - script: yarn lint
    displayName: Lint plugin

  - script: yarn build:plugin
    displayName: Build plugin

  - script: yarn jest --ci --reporters=default --reporters=jest-junit --coverage --coverageReporters=cobertura --coverageReporters=text
    displayName: Test plugin

  - task: PublishTestResults@2
    displayName: Publish plugin test results
    inputs:
      testResultsFiles: junit.xml

  - task: PublishCodeCoverageResults@1
    displayName: Publish plugin test coverage results
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: coverage/cobertura-coverage.xml
